spring.application.name=car

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.url=${CLOUDINARY_URL}
jwt.secret.key=${JWT_SECRET}

# Allow large image uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB