spring.application.name=car

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.url=${CLOUDINARY_URL}
jwt.secret.key=${JWT_SECRET}

# Allow large image uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=5MB

# Spring AI / OpenRouter
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=google/gemini-2.5-flash
spring.ai.openai.chat.options.max-tokens=500

# Redis properties
spring.data.redis.url=${REDIS_URL}